/* eslint-disable */

const frame5x5 = [
    [
        [{ "x": 0, "y": 0, "color": "#FFFFFF" }, { "x": 1, "y": 0, "color": "#FFFFFF" }, { "x": 2, "y": 0, "color": "#FFFFFF" }, { "x": 3, "y": 0, "color": "#FFFFFF" }, { "x": 4, "y": 0, "color": "#FFFFFF" }, { "x": 0, "y": 1, "color": "#FFFFFF" }, { "x": 1, "y": 1, "color": "#FFFFFF" }, { "x": 2, "y": 1, "color": "#FFFFFF" }, { "x": 3, "y": 1, "color": "#FFFFFF" }, { "x": 4, "y": 1, "color": "#FFFFFF" }, { "x": 0, "y": 2, "color": "#FFFFFF" }, { "x": 1, "y": 2, "color": "#FFFFFF" }, { "x": 2, "y": 2, "color": "#FFFFFF" }, { "x": 3, "y": 2, "color": "#FFFFFF" }, { "x": 4, "y": 2, "color": "#FFFFFF" }, { "x": 0, "y": 3, "color": "#FFFFFF" }, { "x": 1, "y": 3, "color": "#FFFFFF" }, { "x": 2, "y": 3, "color": "#FFFFFF" }, { "x": 3, "y": 3, "color": "#FFFFFF" }, { "x": 4, "y": 3, "color": "#FFFFFF" }, { "x": 0, "y": 4, "color": "#FFFFFF" }, { "x": 1, "y": 4, "color": "#FFFFFF" }, { "x": 2, "y": 4, "color": "#FFFFFF" }, { "x": 3, "y": 4, "color": "#FFFFFF" }, { "x": 4, "y": 4, "color": "#FFFFFF" }],
        [{ "x": 0, "y": 0, "color": "#EEFF00" }, { "x": 1, "y": 0, "color": "#EEFF00" }, { "x": 2, "y": 0, "color": "#EEFF00" }, { "x": 3, "y": 0, "color": "#EEFF00" }, { "x": 4, "y": 0, "color": "#EEFF00" }, { "x": 0, "y": 1, "color": "#EEFF00" }, { "x": 1, "y": 1, "color": "#EEFF00" }, { "x": 2, "y": 1, "color": "#EEFF00" }, { "x": 3, "y": 1, "color": "#EEFF00" }, { "x": 4, "y": 1, "color": "#EEFF00" }, { "x": 0, "y": 2, "color": "#EEFF00" }, { "x": 1, "y": 2, "color": "#EEFF00" }, { "x": 2, "y": 2, "color": "#EEFF00" }, { "x": 3, "y": 2, "color": "#EEFF00" }, { "x": 4, "y": 2, "color": "#EEFF00" }, { "x": 0, "y": 3, "color": "#EEFF00" }, { "x": 1, "y": 3, "color": "#EEFF00" }, { "x": 2, "y": 3, "color": "#EEFF00" }, { "x": 3, "y": 3, "color": "#EEFF00" }, { "x": 4, "y": 3, "color": "#EEFF00" }, { "x": 0, "y": 4, "color": "#EEFF00" }, { "x": 1, "y": 4, "color": "#EEFF00" }, { "x": 2, "y": 4, "color": "#EEFF00" }, { "x": 3, "y": 4, "color": "#EEFF00" }, { "x": 4, "y": 4, "color": "#EEFF00" }],
        [{ "x": 0, "y": 0, "color": "#A900DA" }, { "x": 1, "y": 0, "color": "#A900DA" }, { "x": 2, "y": 0, "color": "#A900DA" }, { "x": 3, "y": 0, "color": "#A900DA" }, { "x": 4, "y": 0, "color": "#A900DA" }, { "x": 0, "y": 1, "color": "#A900DA" }, { "x": 1, "y": 1, "color": "#A900DA" }, { "x": 2, "y": 1, "color": "#A900DA" }, { "x": 3, "y": 1, "color": "#A900DA" }, { "x": 4, "y": 1, "color": "#A900DA" }, { "x": 0, "y": 2, "color": "#A900DA" }, { "x": 1, "y": 2, "color": "#A900DA" }, { "x": 2, "y": 2, "color": "#A900DA" }, { "x": 3, "y": 2, "color": "#A900DA" }, { "x": 4, "y": 2, "color": "#A900DA" }, { "x": 0, "y": 3, "color": "#A900DA" }, { "x": 1, "y": 3, "color": "#A900DA" }, { "x": 2, "y": 3, "color": "#A900DA" }, { "x": 3, "y": 3, "color": "#A900DA" }, { "x": 4, "y": 3, "color": "#A900DA" }, { "x": 0, "y": 4, "color": "#A900DA" }, { "x": 1, "y": 4, "color": "#A900DA" }, { "x": 2, "y": 4, "color": "#A900DA" }, { "x": 3, "y": 4, "color": "#A900DA" }, { "x": 4, "y": 4, "color": "#A900DA" }]
    ]
];

export default frame5x5;